apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp-dp
spec:
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
      - name: myflaskapp
        image: vidhya199/flaskapp:latest
        resources:
          limits:
            memory: "200Mi"
            cpu: "300m"
        ports:
        - containerPort: 5000
