apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myflaskapp-dp
  name: myflaskapp-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
      - image: vidhya199/flaskapp:v1
        name: myflaskapp
