apiVersion: v1
kind: Service
metadata:
  name: myflaskapp-svc
  labels:
    app: myflaskapp 
  namespace: default
spec:
  selector:
    app: myflaskapp
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  type: NodePort
    
